// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    // Ban enforcement — admins are never blocked. FAIL CLOSED on RPC error:
    // a transient DB outage must not silently disable ban enforcement.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sb = supabase as any;
    let isAdmin = false;
    try {
      const { data: adminFlag, error: adminErr } = await sb.rpc('is_admin', { _uid: data.claims.sub });
      if (adminErr) throw adminErr;
      isAdmin = adminFlag === true;
    } catch (e) {
      console.error('[auth-middleware] is_admin RPC failed', {
        userId: data.claims.sub,
        error: e instanceof Error ? e.message : String(e),
      });
      // Treat as non-admin so ban check still runs below.
      isAdmin = false;
    }

    if (!isAdmin) {
      try {
        const { data: banned, error: bannedErr } = await sb.rpc('is_user_banned', { _uid: data.claims.sub });
        if (bannedErr) throw bannedErr;
        if (banned === true) {
          console.warn('[auth-middleware] blocked banned user', { userId: data.claims.sub });
          throw new Error('Forbidden: account suspended');
        }
      } catch (e) {
        if (e instanceof Error && e.message.startsWith('Forbidden')) throw e;
        // FAIL CLOSED: refuse the request if the ban-check RPC errors so a
        // dropped/broken function cannot be used to bypass suspensions.
        console.error('[auth-middleware] is_user_banned RPC failed — denying request', {
          userId: data.claims.sub,
          error: e instanceof Error ? e.message : String(e),
        });
        throw new Error('Forbidden: ban verification unavailable');
      }
    }




    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
